name: Push to production
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on acceptance branch
      - production
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This action requires an unshallow working copy,
      # so the following prerequisites are necessary:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      # Deploy your application
      - uses: lunatech-labs/actions-clever-cloud@master
        with:
          alias: lunatech-blog-engine
          timeout: 180
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
